#!/usr/bin/env bash
# Displays "Best School" 9 times and HI
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
