#!/usr/bin/env bash
# Displays status of school file
file_path='school'

if [ -e "$file_path" ]; then
	echo "school file exists"
	
	if [ -e "$file_path" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$file_path" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

